name: CIFAR10 DKNN Experiment
dataset_name: CIFAR10
architecture: resnet
device: gpu
train_parameters:
  max_epochs: 40
  learning_rate: 0.0001
  lr_scheduler_step_size: 35
  loss_threshold: 100000000
  batch_size: 128
  nb_random_seeds: 2
  weight_decay: 0.0001
  nb_train: 10000
  nb_test: 10000
  gpu_memory_fraction: 0.25
nn_parameters:
  nb_proto_neighbors: 5
  nb_neighbors: 75
  nb_cali: 750
  backend: FALCONN
